name: Daily Image

on:
  schedule:
    - cron: "5 13 * * *"   # daily ~9:05am ET
  workflow_dispatch:        # manual runs
  push:                     # test by committing small changes
    branches: [ main ]
    paths:
      - "scripts/**"
      - "prompts.txt"
      - ".github/workflows/daily-image.yml"
      - "assets/**"

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Sanity check Replicate auth (non-blocking)
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          if [ -z "$REPLICATE_API_TOKEN" ]; then
            echo "::warning::REPLICATE_API_TOKEN is not set. The script will fall back to a local asset."
          else
            status=$(curl -s -o /dev/null -w "%{http_code}" \
              -H "Authorization: Token $REPLICATE_API_TOKEN" \
              https://api.replicate.com/v1/models)
            echo "Replicate /v1/models HTTP status: $status"
            if [ "$status" != "200" ]; then
              echo "::warning::Replicate token check did not return 200. Continuing; script will fall back to asset if needed."
            fi
          fi

      - name: Sanity check files
        run: |
          echo "Repository tree:"
          ls -la
          echo "--- scripts/"
          ls -la scripts || true
          echo "--- assets/"
          ls -la assets || true
          echo "--- prompts.txt head:"
          head -n 5 prompts.txt || true

      - name: Generate today's image with Replicate
        env:
          REPLICATE_API_TOKEN: ${{ secrets.REPLICATE_API_TOKEN }}
        run: |
          python scripts/generate_deepai.py

      - name: Commit & push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Daily image update" || echo "No changes to commit"
          git push
